version: "2.2"

networks:
  app-tier:
    driver: bridge

services:
  db:
    image: mysql:8.0
    container_name: backend-sq
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=evidencias
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    ports:
      - "8003:3306"
    expose:
      - "8003"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/1.sql
    networks:
      - app-tier

volumes:
  db:
    driver: local
